<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <!-- Parent Information -->
  <parent>
    <groupId>org.jboss.ejb3.examples</groupId>
    <artifactId>jboss-ejb3-examples-build</artifactId>
    <version>1.2.0-SNAPSHOT</version>
    <relativePath>../build/pom.xml</relativePath>
  </parent>

  <!-- Model Version -->
  <modelVersion>4.0.0</modelVersion>

  <!-- Artifact Information -->
  <artifactId>jboss-ejb3-examples-ch06-filetransfer</artifactId>
  <name>JBoss EJB 3.x Examples - Chapter 6: FileTransfer EJBs</name>
  <description>Example to accompany O'Reilly "Enterprise Java Beans 6th Edition" Chapter 6</description>

  <!-- Properties -->
  <properties>

    <!-- Versioning -->
    <version.org.apache.ftpserver_ftpserver.core>1.0.4</version.org.apache.ftpserver_ftpserver.core>
    <version.commons.net_commons.net>2.0</version.commons.net_commons.net>

  </properties>

  <!-- Dependencies -->
  <dependencies>
    <!-- For the embedded FTP Server -->
    <dependency>
      <groupId>org.apache.ftpserver</groupId>
      <artifactId>ftpserver-core</artifactId>
      <version>${version.org.apache.ftpserver_ftpserver.core}</version>
    </dependency>
    <!-- ftpserver-core is badly-formed, Maven3 needs this explicitly (m2eclipse 0.10.0) to compile -->
    <dependency>
      <groupId>org.apache.ftpserver</groupId>
      <artifactId>ftplet-api</artifactId>
      <version>${version.org.apache.ftpserver_ftpserver.core}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.mina</groupId>
      <artifactId>mina-core</artifactId>
      <version>2.0.0-RC1</version>
      <exclusions>
        <exclusion>
          <groupId>org.easymock</groupId>
          <artifactId>easymock</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.easymock</groupId>
          <artifactId>easymockclassextension</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <!-- For the FTP Client our SFSB will use under the hood -->
    <dependency>
      <groupId>commons-net</groupId>
      <artifactId>commons-net</artifactId>
      <version>${version.commons.net_commons.net}</version>
    </dependency>
 		<dependency>
			<groupId>jakarta.platform</groupId>
			<artifactId>jakarta.jakartaee-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.primefaces</groupId>
			<artifactId>primefaces</artifactId>
			<classifier>jakarta</classifier>
		</dependency>
        <dependency>
            <groupId>org.jboss.arquillian.junit5</groupId>
            <artifactId>arquillian-junit5-container</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- see: https://github.com/arquillian/arquillian-core/issues/248 -->
        <!-- and https://github.com/arquillian/arquillian-core/pull/246/files -->
        <dependency>
            <groupId>org.jboss.arquillian.protocol</groupId>
            <artifactId>arquillian-protocol-servlet-jakarta</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.shrinkwrap.resolver</groupId>
            <artifactId>shrinkwrap-resolver-impl-maven</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assertj.version}</version>
            <scope>test</scope>
        </dependency>
   
  </dependencies>
  
	<build>
		<finalName>test-ejb</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>${maven-war-plugin.version}</version>
			</plugin>
			<plugin>
				<groupId>org.wildfly.plugins</groupId>
				<artifactId>wildfly-maven-plugin</artifactId>
				<version>${wildfly-maven-plugin.version}</version>
				<configuration>
					<discover-provisioning-info>
						<version>${version.wildfly}</version>
						<verbose>true</verbose>
						<context>cloud</context>
					</discover-provisioning-info>
					<galleon-options>
						<jboss-fork-embedded>true</jboss-fork-embedded>
					</galleon-options>
					<runtime-name>ROOT.war</runtime-name>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>package</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
	  <plugin>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-dependencies</id>
            <phase>package</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <includeScope>runtime</includeScope>
              <outputDirectory>${project.build.directory}/lib</outputDirectory>
              <stripVersion>true</stripVersion>
            </configuration>
          </execution>
        </executions>
      </plugin>

		</plugins>
	</build>

    <profiles>

    <profile>

      <!-- Declare the "Integration Test" Profile -->
      <id>it</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>

      <build>

        <plugins>
        
          <!-- Get AS and put into "target" -->
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <executions>
              <execution>
                <id>unpack</id>
                <phase>pre-integration-test</phase> <!-- So run before testing -->
                <goals>
                  <goal>unpack</goal>
                </goals>
                <configuration>
                  <artifactItems>
                    <artifactItem>
                      <groupId>org.jboss.as</groupId>
                      <artifactId>jboss-as-dist</artifactId>
                      <version>${version.org.jboss.as.7}</version>
                      <type>zip</type>
                      <overWrite>false</overWrite>
                      <outputDirectory>${project.build.directory}</outputDirectory>
                    </artifactItem>
                  </artifactItems>
                </configuration>
              </execution>
            </executions>
          </plugin>
         

          <!-- Surefire -->
          <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <executions>
              <execution>
                <id>integration-test</id>
                <phase>integration-test</phase>
                <goals>
                  <goal>test</goal>
                </goals>
                <configuration>
                  <redirectTestOutputToFile>true</redirectTestOutputToFile>
                  <trimStackTrace>false</trimStackTrace>
                  <printSummary>true</printSummary>
                  <includes>
                    <include>**/*IntegrationTestCase.java</include>
                  </includes>
                  <forkMode>once</forkMode>
                </configuration>
              </execution>
            </executions>
          </plugin>

        </plugins>

      </build>

    </profile>

  </profiles>

</project>
