<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <!-- Parent Information -->
  <parent>
    <groupId>org.jboss.ejb3.examples</groupId>
    <artifactId>jboss-ejb3-examples-build</artifactId>
    <version>1.2.0-SNAPSHOT</version>
    <relativePath>../build/pom.xml</relativePath>
  </parent>

  <!-- Model Version -->
  <modelVersion>4.0.0</modelVersion>

  <!-- Artifact Information -->
  <artifactId>jboss-ejb3-examples-ch07-rsscache</artifactId>
  <name>JBoss EJB 3.x Examples - Chapter 7: RssCache EJBs</name>
  <description>Example to accompany O'Reilly "Enterprise Java Beans 6th Edition" Chapter 7</description>

  <!-- Properties -->
  <properties>

    <!-- Versioning -->
    <version.rome_rome.fetcher>1.0</version.rome_rome.fetcher>

  </properties>

  <!-- Dependencies -->
  <dependencies>

 		<dependency>
			<groupId>jakarta.platform</groupId>
			<artifactId>jakarta.jakartaee-api</artifactId>
		</dependency>
        <dependency>
            <groupId>org.jboss.arquillian.junit5</groupId>
            <artifactId>arquillian-junit5-container</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- see: https://github.com/arquillian/arquillian-core/issues/248 -->
        <!-- and https://github.com/arquillian/arquillian-core/pull/246/files -->
        <dependency>
            <groupId>org.jboss.arquillian.protocol</groupId>
            <artifactId>arquillian-protocol-servlet-jakarta</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.shrinkwrap.resolver</groupId>
            <artifactId>shrinkwrap-resolver-impl-maven</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assertj.version}</version>
            <scope>test</scope>
        </dependency>

    <!-- Rome library for RSS parsing -->
    <dependency>
      <groupId>rome</groupId>
      <artifactId>rome-fetcher</artifactId>
      <version>${version.rome_rome.fetcher}</version>
    </dependency>
    
<!-- https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-server -->
<dependency>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-server</artifactId>
    <version>12.0.16</version>
</dependency>
    
    <dependency>
      <groupId>commons-codec</groupId>
      <artifactId>commons-codec</artifactId>
      <version>1.4</version>
      <scope>provided</scope>
    </dependency>

  </dependencies>

  <!-- Extra Repository Definitions (eg. for Rome) -->
  <repositories>
    <repository>
      <id>java.net</id>
      <url>http://download.java.net/maven/2</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <releases>
        <enabled>true</enabled>
      </releases>
    </repository>
  </repositories>
	<build>
		<finalName>test-ejb</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>${maven-war-plugin.version}</version>
			</plugin>
			<plugin>
				<groupId>org.wildfly.plugins</groupId>
				<artifactId>wildfly-maven-plugin</artifactId>
				<version>${wildfly-maven-plugin.version}</version>
				<configuration>
					<discover-provisioning-info>
						<version>${version.wildfly}</version>
						<verbose>true</verbose>
						<context>cloud</context>
					</discover-provisioning-info>
					<galleon-options>
						<jboss-fork-embedded>true</jboss-fork-embedded>
					</galleon-options>
					<runtime-name>ROOT.war</runtime-name>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>package</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
	  <plugin>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-dependencies</id>
            <phase>package</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <includeScope>runtime</includeScope>
              <outputDirectory>${project.build.directory}/lib</outputDirectory>
              <stripVersion>true</stripVersion>
            </configuration>
          </execution>
        </executions>
      </plugin>

		</plugins>
	</build>


  <profiles>

    <profile>

      <!-- Declare the "Integration Test" Profile -->
      <id>it</id>

      <build>

        <plugins>

          <!--

            Configure Surefire to run in integration-test phase
          -->
          <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <executions>
              <execution>
                <id>surefire-it</id>
                <phase>integration-test</phase>
                <goals>
                  <goal>test</goal>
                </goals>
                <configuration>
                  <skip>false</skip>
                  <!-- Include jbossall-client.jar on the CP -->
                  <additionalClasspathElements>
                    <additionalClasspathElement>${jboss.home}/client/jbossall-client.jar</additionalClasspathElement>
                  </additionalClasspathElements>
                  <redirectTestOutputToFile>true</redirectTestOutputToFile>
                  <printSummary>true</printSummary>
                  <forkMode>always</forkMode>
                  <includes>
                    <include>**/*IntegrationTestCase.java</include>
                  </includes>
                </configuration>
              </execution>
            </executions>
          </plugin>

          <!--

            Define the JBossAS Maven Control Plugin
          -->
          <plugin>

            <groupId>org.jboss.maven.plugins.jbossas</groupId>
            <artifactId>maven-jboss-as-control-plugin</artifactId>
            <version>0.1.2-SNAPSHOT</version>

            <!-- Executions -->
            <executions>

              <!--

                Start JBossAS with our new configuration
              -->
 
              <!--
                Deploy into our custom JBossAS Configuration
              -->
              <execution>
                <id>deploy-test-slsb</id>
                <goals>
                  <goal>deploy</goal>
                </goals>
                <phase>pre-integration-test</phase>
                <configuration>
                  <serverConfigName>default</serverConfigName>
                  <files>${project.build.directory}/lib/ftplet-api.jar,
                    ${project.build.directory}/lib/ftpserver-core.jar,
                    ${project.build.directory}/lib/mina-core.jar,
                    ${project.build.directory}/lib/slf4j-api.jar,
                    ${project.build.directory}/lib/commons-net.jar,
                    ${project.build.directory}/${project.build.finalName}.${project.packaging}</files>
                  <jboss.test.run>true</jboss.test.run>
                </configuration>
              </execution>

              <!--

                Stop JBossAS
              -->
 
            </executions>

          </plugin>

        </plugins>

      </build>

    </profile>

  </profiles>

</project>
