<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <!-- Parent Information -->
  <parent>
    <groupId>org.jboss.ejb3.examples</groupId>
    <artifactId>jboss-ejb3-examples-build</artifactId>
    <version>1.2.0-SNAPSHOT</version>
    <relativePath>../build/pom.xml</relativePath>
  </parent>

  <!-- Model Version -->
  <modelVersion>4.0.0</modelVersion>

  <!-- Artifact Information -->
  <artifactId>jboss-ejb3-examples-ch08-messagedestinationlink</artifactId>
  <name>JBoss EJB 3.x Examples - Chapter 8: MessageDestinationLink EJBs</name>
  <description>Example to accompany O'Reilly "Enterprise Java Beans 6th Edition" Chapter 8</description>

  <!-- Build -->
  <build>
  </build>


  <!-- Properties -->
  <properties>

    <!-- JBOSS_HOME (We'll unpack into here -->
    <JBOSS_HOME>${project.build.directory}/jboss-${version.org.jboss.jbossas}</JBOSS_HOME>

    <!-- Versioning -->

  </properties>

  <!-- Dependencies -->
  <dependencies>
		<dependency>
			<groupId>jakarta.platform</groupId>
			<artifactId>jakarta.jakartaee-api</artifactId>
		</dependency>
        <dependency>
            <groupId>org.jboss.arquillian.junit5</groupId>
            <artifactId>arquillian-junit5-container</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- see: https://github.com/arquillian/arquillian-core/issues/248 -->
        <!-- and https://github.com/arquillian/arquillian-core/pull/246/files -->
        <dependency>
            <groupId>org.jboss.arquillian.protocol</groupId>
            <artifactId>arquillian-protocol-servlet-jakarta</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.shrinkwrap.resolver</groupId>
            <artifactId>shrinkwrap-resolver-impl-maven</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assertj.version}</version>
            <scope>test</scope>
        </dependency>
  </dependencies>

    <profiles>

    <profile>

      <!-- Declare the "Integration Test" Profile -->
      <id>it</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>

      <build>

        <plugins>
        
          <!-- Get AS and put into "target" -->
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <executions>
              <execution>
                <id>unpack</id>
                <phase>pre-integration-test</phase> <!-- So run before testing -->
                <goals>
                  <goal>unpack</goal>
                </goals>
                <configuration>
                  <artifactItems>
                    <artifactItem>
                      <groupId>org.jboss.as</groupId>
                      <artifactId>jboss-as-dist</artifactId>
                      <version>${version.org.jboss.as.7}</version>
                      <type>zip</type>
                      <overWrite>false</overWrite>
                      <outputDirectory>${project.build.directory}</outputDirectory>
                    </artifactItem>
                  </artifactItems>
                </configuration>
              </execution>
            </executions>
          </plugin>
         

          <!-- Surefire -->
          <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <executions>
              <execution>
                <id>integration-test</id>
                <phase>integration-test</phase>
                <goals>
                  <goal>test</goal>
                </goals>
                <configuration>
                  <redirectTestOutputToFile>true</redirectTestOutputToFile>
                  <trimStackTrace>false</trimStackTrace>
                  <printSummary>true</printSummary>
                  <includes>
                    <include>**/*IntegrationTest.java</include>
                  </includes>
                  <forkMode>once</forkMode>
                  <skipTests>true</skipTests>
                </configuration>
              </execution>
            </executions>
          </plugin>

        </plugins>

      </build>

    </profile>

  </profiles>

</project>
